### ISSUE TITLE
Installation troubles

### ISSUE THREAD

**Issue by Phando** [ssitu/ComfyUI_NestedNodeBuilder#1]
This is looking like an awesome node, thank you for the contribution. I am having trouble with the install and wanted to know if I was doing something wrong. 
My setup has comfyui on c:/genai.... my custom_nodes is a hard link to a folder on d:/genai.../custom_nodes. This setup has been working great for other nodes, but I am unable to see the menu choices shown in your demo. I tried changing ../../scrips in your js files to /scripts (like the other nodes), but that didn't help. 

If you have any ideas I would be stoked to see this in action.

**Comment by ssitu** [comment]
I just pushed an update to fix your problem. I'm still concerned that there might be a random `web` folder somewhere in your D: drive.

**Comment by Phando** [comment]
You latest fixed it, thank you!
