### ISSUE TITLE
it doesnt work when comfy is being used as backend for stableswarm

### ISSUE THREAD

**Issue by Maki9009** [ssitu/ComfyUI_NestedNodeBuilder#12]
it wont allow me to nest prompts together when I'm using the comfyworkflow on stableswarmui

**Comment by ssitu** [comment]
This extension is only for litegraph, which is what ComfyUI uses for the frontend. I don’t think stable swarm uses nodes either, so this extension wouldn’t apply there.

**Comment by Maki9009** [comment]
> This extension is only for litegraph, which is what ComfyUI uses for the frontend. I don’t think stable swarm uses nodes either, so this extension wouldn’t apply there.

It does you can let it use ur comfy workflow for generating the images

**Comment by ssitu** [comment]
Does it give you an error when you try to nest nodes?

**Comment by Maki9009** [comment]
> Does it give you an error when you try to nest nodes?

No just nothing happens

**Comment by ssitu** [comment]
I’ll have to go install it to figure out the issue.
