### ISSUE TITLE
TypeError:Cannot read properties of undefined (reading'widgets')

### ISSUE THREAD

**Issue by xueqing0622** [ssitu/ComfyUI_NestedNodeBuilder#16]
after Nested node use queue it appear:
TypeError:Cannot read properties of undefined (reading'widgets'), 
when I unnest, it can queue

**Comment by ssitu** [comment]
Can you provide a workflow that this happens with?

**Comment by xueqing0622** [comment]
[roop-test.zip](https://github.com/ssitu/ComfyUI_NestedNodeBuilder/files/12779622/roop-test.zip)
of course, I don't know why, I can use it before, but appear this problem 2 days ago,

**Comment by Duemellon** [comment]
having same problem.

**Comment by MrGingerSir222** [comment]
I have also been having this issue for a while. I just assumed Nested Nodes was no longer compatible.

**Comment by Duemellon** [comment]
they need to cooperate on this one. I use the Inspire pack heavily.

**Comment by MrGingerSir222** [comment]
Agreed. I put in an "error" on the Inspire Pack hoping that they will look into it as well.

**Comment by ssitu** [comment]
@xueqing0622 I don't get the error with the workflow.

Can someone give me the full error log so I can try to fix it?

**Comment by ssitu** [comment]
> It doesn't have any error message on the command line, it just pops up on the web page.

You can find the error in the developer console. You can pull it up by pressing F12 when on the ComfyUI page

**Comment by xueqing0622** [comment]
here is the result when I press F12

 [🐍 pysssss] Skipping LinkRenderMode as core extension found
logging.js:315 No bad links detected.
logging.js:315 [NestedNodeBuilder] Nested node setup
logging.js:315 [NestedNodeBuilder] Nesting workflow
logging.js:315 [NestedNodeBuilder] unnestedToNestedIds: Object
DevTools 无法加载来源映射：无法加载 chrome-extension://cofdbpoegempjloogbagkncekinflcnj/build/content.js.map 的内容：系统错误: net::ERR_BLOCKED_BY_CLIENT
DevTools 无法加载来源映射：无法加载 http://127.0.0.1:8188/sm/4595deba885e6b95e012cf1ed9deed8a7b30edf3ae4c7d4bd5cc11d619b75c11.map 的内容：HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
logging.js:315 [NestedNodeBuilder] Nesting workflow
logging.js:315 [NestedNodeBuilder] unnestedToNestedIds: {46: '8', 47: '8'}
logging.js:315 [NestedNodeBuilder] Nesting workflow
logging.js:315 [NestedNodeBuilder] unnestedToNestedIds: {46: '8', 47: '8'}
logging.js:315 [NestedNodeBuilder] Nesting workflow
logging.js:315 [NestedNodeBuilder] unnestedToNestedIds: {46: '8', 47: '8'}

**Comment by xueqing0622** [comment]
use another web browser same error but and another show this:

Autofocus processing was blocked because a document already has a focused element.
logging.js:315 [NestedNodeBuilder] Saving nested node def: Objectcategory: "Nested Nodes"description: {nestedNodes: Array(2)}display_name: "test1"input: {required: {…}}name: "test1"output: ['LATENT']output_is_list: [false]output_name: ['LATENT'][[Prototype]]: Object
logging.js:315 test
logging.js:315 [NestedNodeBuilder] Nested node setup
2logging.js:315 [NestedNodeBuilder] Nesting workflow
logging.js:315 [NestedNodeBuilder] unnestedToNestedIds: Object3: "10"5: "10"[[Prototype]]: Object

**Comment by xueqing0622** [comment]
here are 2 log I save to files:

[127.0.0.1-1696480323452.log](https://github.com/ssitu/ComfyUI_NestedNodeBuilder/files/12812320/127.0.0.1-1696480323452.log)
[127.0.0.1-1696480391524.log](https://github.com/ssitu/ComfyUI_NestedNodeBuilder/files/12812322/127.0.0.1-1696480391524.log)

**Comment by ssitu** [comment]
Sorry, it doesn't state the error anywhere, but I appreciate the thoroughness. After some debugging it is because of an interaction between this extension and the inspire pack, but it's more of a problem for this extension.

Error:
```
TypeError: Cannot read properties of undefined (reading 'widgets')
    at ComfyApi.queuePrompt_with_seed (seed.js:36:49)
    at api.queuePrompt (nodeMenu.js:48:61)
    at ComfyApp.queuePrompt (app.js:1588:29)
    at async app.queuePrompt (nodeMenu.js:54:13)
```
The [seed.js is from the inspire pack](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/blob/491700a7a5ed3aa7c835768bc2b8337849ca018e/js/seed.js).

And easy fix would be to change [line 36](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/blob/491700a7a5ed3aa7c835768bc2b8337849ca018e/js/seed.js#L36) from 
```let widgets = app.graph._nodes_by_id[node_id].widgets;```
 to
```let widgets = app.graph._nodes_by_id[node_id]?.widgets;```
But then the global seed feature in the pack won't work for nested nodes.

I can have it be compatible with the global seed feature, but at the cost of saving the unnested workflow (instead of the workflow with nested nodes) to the history and image metadata.

I could completely fix it, but it will require an ugly change to the base ComfyUI so I can give it a substitute workflow to save.

**Comment by xueqing0622** [comment]
Thx, it works,  

by the way, it is very  very very important for this extension.
https://github.com/ssitu/ComfyUI_NestedNodeBuilder/issues/6

I think it is very important to hide some input and output,  when the node nest is big is very important,

**Comment by xueqing0622** [comment]
After updating Comfyui and some extensions today, I found that many projects were no longer usable. After testing, I found that deleting your Nestnode  extension ， and everything is normal. I hope you can take the time to fix it

**Comment by ltdrdata** [comment]
Hotfix is applied. And Global Seed will work. But nest node's seed value won't updated visually.
