### ISSUE TITLE
Nodes are separated.

### ISSUE THREAD

**Issue by za-wa-n-go** [ssitu/ComfyUI_NestedNodeBuilder#3]
Dragging and dropping an image and loading the workflow will cause the combined nodes to separate.

**Comment by ssitu** [comment]
This is so that workflows can be shared without needing this extension.

**Comment by za-wa-n-go** [comment]
I see!
But it's stressful for the person installed the node.
It would be great if we could prevent people who have already installed nodes from being disconnected.

**Comment by ssitu** [comment]
I will work on this next.

**Comment by ssitu** [comment]
This is now implemented.
