### ISSUE TITLE
Error after pasting someone's json - seen before?

### ISSUE THREAD

**Issue by tastez** [ssitu/ComfyUI_NestedNodeBuilder#8]
Hi - i have a json with some nested nodes but after pasting or dragging it into comfy i get this pop up

```
Loading aborted due to error reloading workflow data


TypeError: Cannot read properties of null (reading 'type')
TypeError: Cannot read properties of null (reading 'type')
    at ComfyNode.inheritPrimitiveWidgets (http://127.0.0.1:8188/extensions/ComfyUI_NestedNodeBuilder/nestedNode.js:187:26)
    at ComfyNode.nestedNodeSetup (http://127.0.0.1:8188/extensions/ComfyUI_NestedNodeBuilder/nestedNode.js:85:14)
    at ComfyNode.onAdded (http://127.0.0.1:8188/extensions/ComfyUI_NestedNodeBuilder/nestedNode.js:125:18)
    at LGraph.add (http://127.0.0.1:8188/lib/litegraph.core.js:1453:18)
    at LGraph.configure (http://127.0.0.1:8188/lib/litegraph.core.js:2232:22)
    at ComfyApp.loadGraphData (http://127.0.0.1:8188/scripts/app.js:1227:15)
    at http://127.0.0.1:8188/extensions/ComfyUI_NestedNodeBuilder/nodeMenu.js:207:17
This may be due to the following script:
/extensions/ComfyUI_NestedNodeBuilder/nestedNode.js
```
does this look familiar?

**Comment by ssitu** [comment]
Are you able to share the workflow that you're getting errors with?

**Comment by tastez** [comment]
of course! here is the workflow as a screenshot from this thread
https://www.reddit.com/r/StableDiffusion/comments/15tifet/my_new_workflow_utilizing_the_foocus_sampler_in/
https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2Fmy-new-workflow-utilizing-the-foocus-sampler-in-comfy-with-v0-vw3k463u3nib1.png%3Fs%3D31d35c30358481e0d7aae5bfd49adfb0cc434614

and this is the raw json https://pastebin.com/JmdMAtnQ

before installing Nested nodes I would get the graph inside comfy but the nested node would be flagged as missing, Now im getting the nested node but cant unnest it and also have most of the graphi missing. Maybe some copypasta error..

**Comment by ssitu** [comment]
Loads fine for me, but I am unable to unnest the prompt node because I don't have some custom nodes. I guess I should have a way to notify what nodes are missing. I wonder if it is because you are missing the custom nodes used.

Try installing and enabling this:
https://github.com/twri/sdxl_prompt_styler

After you download that, see if loading the workflow works for you.

**Comment by tastez** [comment]
yeah no idea what happened it loads for me too now...
that must have been it! i installed all the sdxl extensions and accidentally copy pasted the json and there was no error

**Comment by tastez** [comment]
actually - if you reload comfy ui with this workflow still open - or duplicate the browser tab, the node is not found. Is this because its inside the copy pasta but never actually added to the custom node location?

**Comment by tastez** [comment]
unnesting and nesting and saving with the same name fixes the issue
