### ISSUE TITLE
Nodes break after workflow is loaded

### ISSUE THREAD

**Issue by CaptainGrock** [ssitu/ComfyUI_NestedNodeBuilder#9]
See video

https://github.com/ssitu/ComfyUI_NestedNodeBuilder/assets/142545094/4ae0a33e-d252-437f-bccf-ee0a3ff1b185

**Comment by ssitu** [comment]
Mind sharing the workflow, I'll have to test what the problem is.

**Comment by CaptainGrock** [comment]
Absolutely (including both workflows, happens to both)
[sdxl_composite_workflows.zip](https://github.com/ssitu/ComfyUI_NestedNodeBuilder/files/12373940/sdxl_composite_workflows.zip)

Thank you so much! It's such a pain to have to re-think/re-connect them.
Jeff

**Comment by ssitu** [comment]
See if #10 fixes your problem.

**Comment by CaptainGrock** [comment]
Just tried and unfortunately it does the same thing

**Comment by ssitu** [comment]
I did notice that the workflows you gave me already had the links disconnected. Could you connect them and send me a picture or the workflow that so I know what it should look like?

**Comment by CaptainGrock** [comment]
Hi - sorry about that, I think I narrowed it down to what's actually causing the break. Check out this new video. I think when you nest items using an previously used node nest group it reverts to the original settings (it won't use any new settings)

https://github.com/ssitu/ComfyUI_NestedNodeBuilder/assets/142545094/91d6fc7a-2a59-490d-ae39-80fcb6995dcf

I'm refixing the other links and will upload the JSON in a few

**Comment by ssitu** [comment]
Strange, I’ll have to look into that.

**Comment by CaptainGrock** [comment]
Here's the JSON
[DEBUG_SDXL_Composite (2 Subjects and Background).zip](https://github.com/ssitu/ComfyUI_NestedNodeBuilder/files/12374428/DEBUG_SDXL_Composite.2.Subjects.and.Background.zip)

**Comment by ssitu** [comment]
I just fixed a bug in #10 and it looks like it's working now:

https://github.com/ssitu/ComfyUI_NestedNodeBuilder/assets/57548627/895f567a-8d70-4145-b113-32292508ca0a

**Comment by CaptainGrock** [comment]
Awesome - how can I apply this to my environment or do I have to wait until the next major publish that I'd grab from Comfy Manager?

**Comment by ssitu** [comment]
I'll merge it now and then you'll be able to update with manager.

**Comment by CaptainGrock** [comment]
Thanks - I confirmed we're good, thank you so much for the quick response!
